package com.arkofdragons.mtgplayer.cardParser

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
data class ScryfallCard(
    @SerialName("object") val dataType: String? = null,
    val id: String? = null,
    val oracle_id: String? = null,
    val multiverse_ids: List<Int>? = null,
    val resource_id: String? = null,
    val arena_id: Int? = null,
    val mtgo_id: Int? = null,
    val mtgo_foil_id: Int? = null,
    val tcgplayer_id: Int? = null,
    val tcgplayer_etched_id: Int? = null,
    val cardmarket_id: Int? = null,
    val name: String? = null,
    val flavor_name: String? = null,
    val lang: String? = null,
    val released_at: String? = null,
    val uri: String? = null,
    val scryfall_uri: String? = null,
    val layout: String? = null,
    val highres_image: Boolean? = null,
    val image_status: String? = null,
    val image_uris: Map<String, String>? = null,
    val mana_cost: String? = null,
    val cmc: Float? = null,
    val type_line: String? = null,
    val oracle_text: String? = null,
    val printed_text: String? = null,
    val power: String? = null,
    val toughness: String? = null,
    val loyalty: String? = null,
    val life_modifier: String? = null,
    val hand_modifier: String? = null,
    val colors: List<String>? = null,
    val color_indicator: List<String>? = null,
    val color_identity: List<String>? = null,
    val defense: String? = null,
    val keywords: List<String>? = null,
    val produced_mana: List<String>? = null,
    val card_faces: JsonElement? = null,
    val all_parts: List<Map<String, String>>? = null,
    val legalities: Map<String, String>? = null,
    val games: List<String>? = null,
    val reserved: Boolean? = null,
    val game_changer: Boolean? = null,
    val foil: Boolean? = null,
    val nonfoil: Boolean? = null,
    val finishes: List<String>? = null,
    val oversized: Boolean? = null,
    val promo: Boolean? = null,
    val reprint: Boolean? = null,
    val variation: Boolean? = null,
    val set_id: String? = null,
    val set: String? = null,
    val set_name: String? = null,
    val set_type: String? = null,
    val set_uri: String? = null,
    val set_search_uri: String? = null,
    val scryfall_set_uri: String? = null,
    val rulings_uri: String? = null,
    val prints_search_uri: String? = null,
    val collector_number: String? = null,
    val digital: Boolean? = null,
    val rarity: String? = null,
    val attraction_lights: List<Int>? = null,
    val watermark: String? = null,
    val flavor_text: String? = null,
    val card_back_id: String? = null,
    val artist: String? = null,
    val artist_ids: List<String>? = null,
    val illustration_id: String? = null,
    val border_color: String? = null,
    val frame: String? = null,
    val frame_effects: List<String>? = null,
    val security_stamp: String? = null,
    val full_art: Boolean? = null,
    val textless: Boolean? = null,
    val booster: Boolean? = null,
    val story_spotlight: Boolean? = null,
    val content_warning: Boolean? = null,
    val promo_types: List<String>? = null,
    val edhrec_rank: Int? = null,
    val penny_rank: Int? = null,
    val preview: Map<String, String>? = null,
    val prices: Map<String, Float?>? = null,
    val related_uris: Map<String, String>? = null,
    val purchase_uris: Map<String, String>? = null,
) {

}